### ISSUE TITLE
React 19 Old Error Back: Uncaught Error: Map container is already initialized.

### ISSUE THREAD

**Issue by GeorgSteyn** [PaulLeCam/react-leaflet#1133]
## Bug report in v4
- [X] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [ ] Using the latest version of React and ReactDOM v18.
- [X] Using the supported version of Leaflet (v1.8.0 minimum) and its corresponding CSS file is loaded.
- [X] Using the [latest v4 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [X] The issue has not already been reported.
- [X] Make sure you have followed the [quick start guide](https://leafletjs.com/examples/quick-start.html) for Leaflet.
- [X] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/start-introduction) and that you understand the [limitations](https://react-leaflet.js.org/docs/start-introduction#limitations).

### Expected behavior
Working

### Actual behavior
Well upgraded project to React 19 RC and the error popped up. Same as the past with ReactJs Upgrades
Not working getting error: Uncaught Error: Map container is already initialized.

### Steps to reproduce
Upgrade project to React 19

**Comment by cedric-marcone** [comment]
I tried to upgrade a big app from react 18.3.0 to latest react 19 rc (19.0.0-rc-915b914b3a-20240515) and I'm facing the same issue.

Here is the simplest repro : https://codesandbox.io/p/sandbox/thirsty-zeh-34ddlm

Thanks for your help.

**Comment by kevinbioj** [comment]
The issue seems to go away by disabling Strict Mode.
Even tho this is not a viable solution, it's a way to get it working until it gets fixed 👍

**Comment by bovan** [comment]
workaround:
```
  const isInitialized = useRef(false);
  useEffect(() => {
    isInitialized.current = true;
    return () => {
      isInitialized.current = false;
    };
  }, []);
  if (!isInitialized) return null;
```

**Comment by icodeforlove** [comment]
> The issue seems to go away by disabling Strict Mode. Even tho this is not a viable solution, it's a way to get it working until it gets fixed 👍

I encountered the same issue while testing this in the Next.js v15 RC.

The Map container fails to mount, even with dynamic loading.

A temporary workaround as you mentioned is to disable reactStrictMode for the entire app by setting { reactStrictMode: false } in next.config.

Hopefully, we can find a proper solution soon.

**Comment by Nedi11** [comment]
I am having this issue aswell

**Comment by whollacsek** [comment]
Hello do we have a solution soon for this issue? Next.js 15 just released so I'd assume more people will run into this as well

**Comment by mamlzy** [comment]
> Hello do we have a solution soon for this issue? Next.js 15 just released so I'd assume more people will run into this as well

sorry for tagging you @PaulLeCamm

**Comment by valentingavran** [comment]
I'm using Next.js 15 with `react-leaflet` v5.0.0-rc.1, and I haven't encountered any issues with it. Have you tried this release candidate version?

**Comment by mamlzy** [comment]
> I'm using Next.js 15 with `react-leaflet` v5.0.0-rc.1, and I haven't encountered any issues with it. Have you tried this release candidate version?

yes, it is working fine on `rc` tag, thanks

**Comment by SuMayaBee** [comment]
Thanks you so much

**Comment by erbilozum** [comment]
I am having this issue

**Comment by homebooksalexalmu** [comment]
> I'm using Next.js 15 with `react-leaflet` v5.0.0-rc.1, and I haven't encountered any issues with it. Have you tried this release candidate version?

I am in the same case, but it does not work for me. 

I start the leaflet configuration with react-leaflet in local development and everything works, but when I do a `yarn build` it fails because `window is not defined`. When I fix this error I get the error “Error: Map container is already initialized.” and from here I can not pass.

**Comment by zeyadAjamy** [comment]
I faced the same issue, but it was fixed after clearing the cache. Try deleting the .next dir

**Comment by homebooksalexalmu** [comment]
> I faced the same issue, but it was fixed after clearing the cache. Try deleting the .next dir

I just tried it, but unfortunately it is still the same. I get the “Map container is already initialized.” error.

**Comment by valentingavran** [comment]
> I'm using Next.js 15 with `react-leaflet` v5.0.0-rc.1, and I haven't encountered any issues with it. Have you tried this release candidate version?

I would also recommend deactivating the SSR for the map. Perhaps some of you have not yet done this and it may solve the `Map container is already initialized` problem

```typescript
import dynamic from 'next/dynamic';
const LazyMap = dynamic(() => import('./maps/map').then((mod) => mod.Map), { ssr: false });
```

**Comment by sebastianovide** [comment]
> > I'm using Next.js 15 with `react-leaflet` v5.0.0-rc.1, and I haven't encountered any issues with it. Have you tried this release candidate version?
> 
> I would also recommend deactivating the SSR for the map. Perhaps some of you have not yet done this and it may solve the `Map container is already initialized` problem
> 
> ```ts
> import dynamic from 'next/dynamic';
> const LazyMap = dynamic(() => import('./maps/map').then((mod) => mod.Map), { ssr: false });
> ```

My is dissabled.. I'll try with the rc1 version

**Comment by homebooksalexalmu** [comment]
I was already using next/dynamic before. I have been changing versions and creating a new Next.js App Router project.

I have managed to get it working both running `yarn dev` and `yarn build` with these dependencies:

```
“dependencies": {
    “react": ‘19.0.0-rc-69d4b800-20241021’,
    “react-dom": ‘19.0.0-rc-69d4b800-20241021’,
    “next": ‘15.0.1’,
    “leaflet": ‘^1.9.4’,
    “leaflet-defaulticon-compatibility": ‘^0.1.2’,
    “react-leaflet": ‘v5.0.0-rc.1’.
  },
```

**Comment by muhaimincs** [comment]
> Hello do we have a solution soon for this issue? Next.js 15 just released so I'd assume more people will run into this as well

yeah

> I was already using next/dynamic before. I have been changing versions and creating a new Next.js App Router project.
> 
> I have managed to get it working both running `yarn dev` and `yarn build` with these dependencies:
> 
> ```
> “dependencies": {
>     “react": ‘19.0.0-rc-69d4b800-20241021’,
>     “react-dom": ‘19.0.0-rc-69d4b800-20241021’,
>     “next": ‘15.0.1’,
>     “leaflet": ‘^1.9.4’,
>     “leaflet-defaulticon-compatibility": ‘^0.1.2’,
>     “react-leaflet": ‘v5.0.0-rc.1’.
>   },
> ```

This temporarily work for me

**Comment by AtheerAPeter** [comment]
> I'm using Next.js 15 with `react-leaflet` v5.0.0-rc.1, and I haven't encountered any issues with it. Have you tried this release candidate version?

Solved my issue, thanks.

**Comment by pekmah** [comment]
> > Hello do we have a solution soon for this issue? Next.js 15 just released so I'd assume more people will run into this as well
> 
> yeah
> 
> > I was already using next/dynamic before. I have been changing versions and creating a new Next.js App Router project.
> > I have managed to get it working both running `yarn dev` and `yarn build` with these dependencies:
> > ```
> > “dependencies": {
> >     “react": ‘19.0.0-rc-69d4b800-20241021’,
> >     “react-dom": ‘19.0.0-rc-69d4b800-20241021’,
> >     “next": ‘15.0.1’,
> >     “leaflet": ‘^1.9.4’,
> >     “leaflet-defaulticon-compatibility": ‘^0.1.2’,
> >     “react-leaflet": ‘v5.0.0-rc.1’.
> >   },
> > ```
> 
> This temporarily work for me

This worked, Thanks

**Comment by yadhukrishnasm** [comment]
> w

it's giving me peer dependency warning and errors with this

**Comment by chuang091** [comment]
```
“react-leaflet": ‘v5.0.0-rc.1’.
```
works for me!

**Comment by ownerofglory** [comment]
> I'm using Next.js 15 with `react-leaflet` v5.0.0-rc.1, and I haven't encountered any issues with it. Have you tried this release candidate version?

Release candidate version of `react-leaflet` worked for me. Thanks

**Comment by lemmski** [comment]
> I'm using Next.js 15 with `react-leaflet` v5.0.0-rc.1, and I haven't encountered any issues with it. Have you tried this release candidate version?

This works with Next.js 15.0.3, thank you!

**Comment by Akhsanfr** [comment]
Updating to react-leaflet version ^5.0.0 works for me now.

**Comment by kotesh-arya** [comment]
> react-leaflet": ‘v5.0.0-rc.1’.

This worked, thanks <3

**Comment by legaceee** [comment]
> The issue seems to go away by disabling Strict Mode. Even tho this is not a viable solution, it's a way to get it working until it gets fixed 👍

Thankyou i was stuck in it from 2 hours

**Comment by lancaluis** [comment]
Has anyone faced issues with map rendering?
I’m using Next.js 15 and react-leaflet **5.0.0-rc.2.**

I'm using the Map component with "use client" already, but still...

![Image](https://github.com/user-attachments/assets/db64329b-2455-4de1-9f17-0b353ed443b7)

**Comment by lancaluis** [comment]
> Has anyone faced issues with map rendering? I’m using Next.js 15 and react-leaflet **5.0.0-rc.2.**
> 
> I'm using the Map component with "use client" already, but still...
> 
> ![Image](https://github.com/user-attachments/assets/db64329b-2455-4de1-9f17-0b353ed443b7)

I solved the problem adding `@import "~leaflet/dist/leaflet.css"` inside `global.css`, but now I'm facing
`ReferenceError: window is not defined` and the icons still doesn't work

**Comment by coderyeasin** [comment]
if anyone faces an issue with **react-leaflet-draw**
my package.json:   
```
"next": "15.1.7",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-leaflet": "^4.0.0",
    "react-leaflet-draw": "^0.20.6",
```
At first, I got a version conflict error when I tried to install 'react-leaflet-draw' so I needed to downgrade versions in nextjs15. Finally, I got this error 'Uncaught Error: Map container is already initialized.' after several attempts, it's not working even though I used dynamic import but got the same error.
so I used this solution in the next.config.

`{ reactStrictMode: false }`

if anyone has an idea about this problem please let me know... hopefully, we will find a good solution for it!

**Comment by mwanas** [comment]
I am working on project react 18.3 and  react-leaflet 4.2 to resolve this issue I added an error boundary around the map container which catches the error and retries after the failure
```
import React, { Component } from 'react';
import AppLoader from "@/components/AppLoader/AppLoader";

class ErrorBoundary extends Component {
  constructor(props) {
    super(props);
    this.state = { hasError: false, error: null, retryCount: 0 };
    this.maxRetries = 3;
    this.retryTimeout = 3000;
  }

  static getDerivedStateFromError(error) {
    return { hasError: true, error };
  }

  componentDidCatch(error, errorInfo) {
    console.error("Error caught by ErrorBoundary:", error, errorInfo);

    if (this.state.retryCount < this.maxRetries) {
      this.autoRetry();
    }
  }

  autoRetry = () => {
    setTimeout(() => {
      this.setState((prevState) => ({
        hasError: false,
        error: null,
        retryCount: prevState.retryCount + 1,
      }));
    }, this.retryTimeout);
  };

  render() {
    if (this.state.hasError) {
      return (
          <AppLoader />
      );
    }

    return this.props.children;
  }
}

export default ErrorBoundary;

```
```
import { useTranslation } from 'react-i18next';
import { Col } from 'react-bootstrap';
import PropTypes from 'prop-types';
import GeoChartContainer from '@/components/Charts/GeoChart/GeoChartContainer'; // ✅ Use the new container
import ErrorBoundary from "@/modules/detections/Components/DetectionsQueue/Utils/ErrorBoundry";
import Style from '@/modules/home/components/GeoGraphCard/Style.module.scss';
import { LAST_X_DAYS } from '@/utils/aisocConstants';
import Card from "@/components/Card/Card";

const DetectionsHeatMap = ({ chartWrapperClass = '', detectionType, graph, className, size = null }) => {
  const { t } = useTranslation('home');

  return (
    <Col lg={size} className={className}>
      <Card
        title={(
          <div className="d-flex justify-content-between mb-3">
            {t(`heatMap.${detectionType.toLowerCase()}`, {
              days: LAST_X_DAYS,
            })}
          </div>
        )}
        className={Style.heatMap}
        cardInnerClass="cardInner"
      >
        <ErrorBoundary>
          <GeoChartContainer
            graph={graph}
            detectionType={detectionType}
            chartWrapperClass={chartWrapperClass}
          />
        </ErrorBoundary>

      </Card>
    </Col>
  );
};

DetectionsHeatMap.propTypes = {
  graph: PropTypes.string,
  chartWrapperClass: PropTypes.string,
  detectionType: PropTypes.string.isRequired,
  size: PropTypes.number,
  className: PropTypes.string,
};

export default DetectionsHeatMap;

```
The solution solved the issue without any upgrade for react or replacing the map. As react-leaflet 5 requires React 19

**Comment by sevdas** [comment]
> I'm using Next.js 15 with `react-leaflet` v5.0.0-rc.1, and I haven't encountered any issues with it. Have you tried this release candidate version?

thank you for posting this, it resolved the same issue for me too! ✨

**Comment by benjaminblack** [comment]
We ran into this issue. Upgrading to `5.0.0` did not fix.

Two workarounds that work for us:

1. memoizing the component:

```tsx
const container = useMemo(() => (
    <MapContainer
        ...
    />
), [/* ... */]);

return container;
```

2. Brute-forcing React to completely re-create the container on every re-render:

```tsx
<MapContainer
   key={crypto.randomUUID()}
   ...
/>
```

**Comment by 0xtz** [comment]
```
Cannot read properties of undefined (reading '_leaflet_events')
```

i updated to the v5 and i got this hhhh

**Comment by mwanas** [comment]
> ```
> Cannot read properties of undefined (reading '_leaflet_events')
> ```
> 
> i updated to the v5 and i got this hhhh

https://github.com/PaulLeCam/react-leaflet/issues/1133#issuecomment-2692643078
Use this solution.

**Comment by mwanas** [comment]
> if anyone faces an issue with **react-leaflet-draw** my package.json:
> 
> ```
> "next": "15.1.7",
>     "react": "^18.0.0",
>     "react-dom": "^18.0.0",
>     "react-leaflet": "^4.0.0",
>     "react-leaflet-draw": "^0.20.6",
> ```
> 
> At first, I got a version conflict error when I tried to install 'react-leaflet-draw' so I needed to downgrade versions in nextjs15. Finally, I got this error 'Uncaught Error: Map container is already initialized.' after several attempts, it's not working even though I used dynamic import but got the same error. so I used this solution in the next.config.
> 
> `{ reactStrictMode: false }`
> 
> if anyone has an idea about this problem please let me know... hopefully, we will find a good solution for it!

Use this solution
https://github.com/PaulLeCam/react-leaflet/issues/1133#issuecomment-2692643078

**Comment by Dotgix-Technologies** [comment]
that worked for me 
That was a tricky issue, and the solution involved shifting from a "React-style" declarative approach to a more direct, "bulletproof" imperative one.

Here’s a detailed breakdown of what we did and why it solved the problem for good. 🎉

-----

### \#\# The Core Problem: React vs. Leaflet Lifecycles

The error "Map container is already initialized" happens because of a conflict between how React works and how the Leaflet library works.

  * **React's Job**: React loves to re-render components when their state or props change. When your "random event" happened, a parent component updated, telling your `Location` component to render again.
  * **Leaflet's Rule**: The Leaflet library, on the other hand, is not built with React in mind. Once it creates a map in a specific `<div>`, it doesn't allow you to initialize another map in that same spot.

When React re-rendered your component, it tried to run the `<MapContainer>` code again on the same `<div>`, which Leaflet strictly forbids, causing the crash.

-----

### \#\# The New Strategy: Taking Control from React

Instead of letting React control the map's creation and destruction on every render, we took manual control.

Think of it like this: Instead of rebuilding a complex Lego model from scratch every time you want to change one piece, we decided to build the model **once** and then just swap the individual pieces as needed.

We did this by completely separating the map's lifecycle from React's re-render cycle.

-----

### \#\# Key Code Changes and What They Do

Here are the four key changes that made it work:

#### 1\. Using `useRef` to "Remember" the Map

```tsx
const mapRef = useRef<L.Map | null>(null);
const mapContainerRef = useRef<HTMLDivElement | null>(null);
```

We created two `ref` objects. Think of a `ref` as a "memory box" that persists across re-renders without causing them.

  * `mapContainerRef`: This just holds a reference to the plain `<div>` in our JSX, giving us a stable spot to build our map.
  * `mapRef`: This is the most important one. It holds the actual Leaflet map **instance** after we create it. Because it's a ref, the map object doesn't get destroyed and recreated every time the component updates.

#### 2\. The One-Time Setup (`useEffect` with `[]`)

```tsx
useEffect(() => {
  if (mapRef.current || !mapContainerRef.current) {
    return;
  }
  
  // Create the map instance ONCE
  const map = L.map(mapContainerRef.current);
  mapRef.current = map; // Store it in our "memory box"

  // Add the tile layer
  L.tileLayer(...).addTo(map);

  // IMPORTANT: The cleanup function
  return () => {
    map.remove();
  };
}, []); // The empty array [] tells React: "ONLY run this code ONCE when the component first mounts."
```

This is the heart of the solution. This `useEffect` hook creates the map **imperatively** (like you would in plain JavaScript). The empty dependency array `[]` is our guarantee that this code will run only a single time, no matter what "random events" happen in parent components. The cleanup function (`map.remove()`) is also crucial for preventing errors when you navigate away from the page.

#### 3\. Handling All Updates in a Separate `useEffect`

```tsx
useEffect(() => {
  if (!mapRef.current || !userPos) {
    return;
  }
  const map = mapRef.current; // Get the persistent map instance

  // Clear old markers/lines
  // ...

  // Add new markers/lines
  L.marker(userPos, ...).addTo(map);
  
  // Update the view
  map.fitBounds(...);

}, [userPos, restaurant]);
```

This second `useEffect` handles everything that needs to change **after** the map is created. It watches for changes to your data (`userPos`, `restaurant`). When a change happens, it doesn't try to rebuild the map. It just grabs the existing map instance from `mapRef.current` and uses standard Leaflet commands like `.addTo(map)` and `fitBounds()` to update what's shown.

#### 4\. Rendering a Simple `div`

```tsx
<div ref={mapContainerRef} style={{ height: "400px", width: "90%" }} />
```

Finally, we removed the `<MapContainer>` component from `react-leaflet` entirely and replaced it with a simple, stable `<div>`. We are no longer fighting with the library's component lifecycle; we are just telling React, "Give me a blank space," and we handle the rest ourselves.

This pattern is the most resilient way to integrate a non-React library like Leaflet and should permanently resolve the re-initialization issue.

**Comment by benedikt90** [comment]
> I'm using Next.js 15 with `react-leaflet` v5.0.0-rc.1, and I haven't encountered any issues with it. Have you tried this release candidate version?

For anyone on React 19: using v5.0.0 solves this issue - no rc needed.

My specific setup:
```
    "leaflet": "^1.9.4",
    "react": "^19.1.0",
    "react-dom": "^19.1.0",
    "react-leaflet": "^5.0.0",
```

**Comment by Milopadma** [comment]
> > I'm using Next.js 15 with `react-leaflet` v5.0.0-rc.1, and I haven't encountered any issues with it. Have you tried this release candidate version?
> 
> For anyone on React 19: using v5.0.0 solves this issue - no rc needed.
> 
> My specific setup:
> 
> ```
>     "leaflet": "^1.9.4",
>     "react": "^19.1.0",
>     "react-dom": "^19.1.0",
>     "react-leaflet": "^5.0.0",
> ```

thank you for this
