### ISSUE TITLE
Third party plugins cannot extend components that use forwardRef

### ISSUE THREAD

**Issue by sanfilippopablo** [PaulLeCam/react-leaflet#488]
- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v16.3.0 minimum).
- [x] Using the supported version of Leaflet (v1.3.x) and its corresponding CSS file is loaded.
- [x] Using the [latest v2 RC version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases) - **not v1**.
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/en/intro.html) and that you understand the [limitations](https://react-leaflet.js.org/docs/en/intro.html#limitations).

### Expected behavior
Third party plugins are supposed to extend from existing classes (components) in the react-leaflet class hierarchy. That's how most react-leaflet plugins work right now.

### Actual behavior
 The problem is that due `React.forwardRef` not returning a function (like normal React components) but an object, [the check babel does](https://github.com/babel/babel/blob/8ab4a5df433accf65a127dfe357dae8ffd6f498b/packages/babel/src/transformation/templates/helper-inherits.js#L2) to make sure a class is extensible fails. That means that every third party plugin extending a react-leaflet component that uses `React.forwardRef` fails.

### Steps to reproduce
[Here's a simple codepen](https://codepen.io/anon/pen/vrJraP?editors=1111) reproducing the issue.

**Comment by sanfilippopablo** [comment]
react-leaflet-draw extends `LayersControl`: https://github.com/alex3165/react-leaflet-draw/blob/master/src/EditControl.js

react-leaflet-bing extends `TileLayer`: https://github.com/Charmatzis/react-leaflet-bing/blob/master/src/Bing.js

Both of those components are wrapped by `withLeaflet`.

**Comment by PaulLeCam** [comment]
They are both made for react-leaflet v1, not v2. This is a major version because it introduces possible breaking changes.

**Comment by sanfilippopablo** [comment]
OK, sure. But let's say I want to extend the `GeoJSON` to have all its current functionality and a little more. For example, to reload the layer if the `data` prop changes. I could extend `GeoJSON` and add this method:
```es6
updateLeafletElement(fromProps, toProps) {
    super.updateLeafletElement(fromProps, toProps);
    if (!isEqual(fromProps.data, toProps.data)) {
      this.leafletElement.clearLayers();
      this.leafletElement.addData(toProps.data);
    }
  }
```
But I can't extend `GeoJSON`, because the only export already uses forwardRef. What if we added a named export [here](https://github.com/PaulLeCam/react-leaflet/blob/master/src/GeoJSON.js#L23). Then I can extend it and use `withLeaflet` in my component.

**Comment by PaulLeCam** [comment]
I don't think it's a good idea to have two `GeoJSON` exports, it's more confusing than anything.
If you want to implement your custom `GeoJSON`, you can start by copying over the current implementation and change what you need.
The primary use for this library is to consume the components directly, not extending them and expecting things will work out of the box. The "abstract" component classes can be extended but the public components should be used as-is.

**Comment by bsotodo** [comment]
I am not sure, but if this is releated to the issue that one can't assign propTypes to components returned from React.ForwardRef: It was fixed in React 16.4.1: https://github.com/facebook/react/blob/master/CHANGELOG.md#1641-june-13-2018

**Comment by sanfilippopablo** [comment]
@bsotodo interesting. Still, doesn't solve the issue.
@PaulLeCam fair enough. Would you accept a PR explaining that in docs?

**Comment by PaulLeCam** [comment]
@sanfilippopablo sorry for the late reply, I updated the docs but yes please open a PR if you think things can be better explained.
