### ISSUE TITLE
Module parse failed: Unexpected token (10:41) in @react-leaflet/core/esm/path.js

### ISSUE THREAD

**Issue by carsten-walther** [PaulLeCam/react-leaflet#877]
## Bug report

**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v17.0.0 minimum).
- [x] Using the supported version of Leaflet (v1.7.1 minimum) and its corresponding CSS file is loaded.
- [x] Using the [latest v3 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/start-introduction) and that you understand the [limitations](https://react-leaflet.js.org/docs/start-introduction#limitations).

### Expected behavior

TypeScript should compile successfully.

### Actual behavior

./node_modules/@react-leaflet/core/esm/path.js 10:41
Module parse failed: Unexpected token (10:41)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   useEffect(function updatePathOptions() {
|     if (props.pathOptions !== optionsRef.current) {
>       const options = props.pathOptions ?? {};
|       element.instance.setStyle(options);
|       optionsRef.current = options;

### Steps to reproduce

- follow https://react-leaflet.js.org/docs/start-setup and run yarn start

**Comment by Gimhan-minion** [comment]
I do have the exact same issue.  @carsten-walther Did you find out a way to fix the bug?

**Comment by carsten-walther** [comment]
No, unfortunately not.

**Comment by Mimieye** [comment]
I have a similar issue about this. But the error occurs in pane.js file
![1取](https://user-images.githubusercontent.com/7856624/118402823-35e1a380-b69e-11eb-9f07-d2f0bb77e405.PNG)

I just import react-leaflet and this error occur, it seem like something wrong with nullish coalescing operator?
I don't know how to fix this, I need some help, thank you!

**Comment by mostfamiliar** [comment]
I'm experiencing this issue as well. Like @Mimieye said it's related to the nullish coalescing operator. When I strip those out, I am able to compile.

**Comment by PaulLeCam** [comment]
This is not an issue with React Leaflet but with your bundler or similar tool's support or configuration, please raise the issue in the relevant repository.

**Comment by stassb129** [comment]
how to fix ?????????????

**Comment by jagribble** [comment]
If anyone is having issues with this make sure that your bundling tool is able to handle the nullish coalescing operator. 

For webpack you can use the `@babel/plugin-proposal-nullish-coalescing-operator`. Although make sure that you don't exclude node_modules in the rule. 

It is related to  [facebook/create-react-app#9468](https://github.com/facebook/create-react-app/issues/9468) for those using CRA

**Comment by Arodriguez14** [comment]
I do have the exact same issue. @carsten-walther Did you find out a way to fix the bug?

**Comment by jagribble** [comment]
@Arodriguez14 This is that most people will exclude node_modules when bundling (correctly). This means that the `??` in the project causes issues as the bundler doesn't know what to do with it. If you allow the rule (babel-loader for webpack for example) to run with node_modules too you should be ok (providing you don't need the plugin). 

Ideally, this wouldn't be the case. By adding ` --plugins @babel/plugin-proposal-nullish-coalescing-operator` to the babel cli script that is run when generating the esm module this would mean that your bundler would not need to include this module. @PaulLeCam is this something that could be added?

**Comment by stassb129** [comment]
> @Arodriguez14 This is that most people will exclude node_modules when bundling (correctly). This means that the `??` in the project causes issues as the bundler doesn't know what to do with it. If you allow the rule (babel-loader for webpack for example) to run with node_modules too you should be ok (providing you don't need the plugin). 
> 
> Ideally, this wouldn't be the case. By adding ` --plugins @babel/plugin-proposal-nullish-coalescing-operator` to the babel cli script that is run when generating the esm module this would mean that your bundler would not need to include this module. @PaulLeCam is this something that could be added?  

But if CRA?

**Comment by jagribble** [comment]
> > @Arodriguez14 This is that most people will exclude node_modules when bundling (correctly). This means that the `??` in the project causes issues as the bundler doesn't know what to do with it. If you allow the rule (babel-loader for webpack for example) to run with node_modules too you should be ok (providing you don't need the plugin).
> > Ideally, this wouldn't be the case. By adding ` --plugins @babel/plugin-proposal-nullish-coalescing-operator` to the babel cli script that is run when generating the esm module this would mean that your bundler would not need to include this module. @PaulLeCam is this something that could be added?
> 
> But if CRA?

I mean sure maybe there is something else? But could also be that CRA is excluding node_modules meaning that it is a similar situation right? Guess what I'm saying is more of an observation rather than the definite solution

**Comment by siner308** [comment]
https://github.com/facebook/create-react-app/issues/9468#issuecomment-694191642 worked for me

**Comment by stassb129** [comment]
> [facebook/create-react-app#9468 (comment)](https://github.com/facebook/create-react-app/issues/9468#issuecomment-694191642) worked for me

thank you so match !!!

**Comment by DenyCelestino** [comment]
@carsten-walther I have the same problem, did you manage to solve it?

**Comment by stassb129** [comment]
> @carsten-walther I have the same problem, did you manage to solve it?

facebook/create-react-app#9468 (comment)

**Comment by DenyCelestino** [comment]
@stassb129  this way it’s not working, I don’t know what’s going on

**Comment by wkhughes** [comment]
> [facebook/create-react-app#9468 (comment)](https://github.com/facebook/create-react-app/issues/9468#issuecomment-694191642) worked for me

This worked for me. Although I also had to delete the node_modules/.cache per the [CRA supported browsers docs](https://create-react-app.dev/docs/supported-browsers-features/#configuring-supported-browsers):
> When editing the browserslist config, you may notice that your changes don't get picked up right away. This is due to an issue in babel-loader not detecting the change in your package.json. A quick solution is to delete the node_modules/.cache folder and try again.

**Comment by Arodriguez14** [comment]
> [facebook/create-react-app#9468 (comment)](https://github.com/facebook/create-react-app/issues/9468#issuecomment-694191642) worked for me

THANK YOU!!!!!!

**Comment by Arodriguez14** [comment]
Removing node_modules/.cache worked for me. Thank to all!!!!

**Comment by DenyCelestino** [comment]
@Arodriguez14  I will try this

**Comment by DenyCelestino** [comment]
@Arodriguez14 thank you very much changing the browser list and deleting the nodule_module / .cache worked

**Comment by tony-stark-edith** [comment]
As mentioned [here](https://github.com/PaulLeCam/react-leaflet/pull/880#issuecomment-842466079), 
**libraries are normally not babelified so the published package should not contain future ES functionality. So I think best would be to create a new release which don't contain this ?? hints. Else everybody need to hack into its webpack package that a specific node_modules need to be babelified.**

**Comment by federicoCapaccio** [comment]
I am facing the same issue but this fix does not help

> [facebook/create-react-app#9468 (comment)](https://github.com/facebook/create-react-app/issues/9468#issuecomment-694191642) worked for me

**Comment by Gimhan-minion** [comment]
@federicoCapaccio Did you delete your node_modules/.cache after replacing the browerlist?

**Comment by bradstewa** [comment]
While I fixed it with instructions above using [this CRA fix](https://github.com/facebook/create-react-app/issues/9468#issuecomment-694191642) like many other here I suspect don't wish to target older browsers and ship the larger bundle size that goes with that.

**Comment by federicoCapaccio** [comment]
> @federicoCapaccio Did you delete your node_modules/.cache after replacing the browerlist?
> 
> https://stackoverflow.com/a/67574280/15937882
> 
> You can refer this link to fix this issue :)

Yes i did it but it didn't work @Gimhan-minion

**Comment by cherouvim** [comment]
Even though the `browserslist` trick "fixed" the issue for me, my storybook was still broken with the same message. There is no way I'd ever want to attempt to fix storybook's configuration, so what I did was pin to the old version of the "core" library as others have mentioned:
```
	"react-leaflet": "3.1.0",
	"@react-leaflet/core": "1.0.2",
```

I hope @PaulLeCam understands soon that react-leaflet is library code used by tons of client code (applications) which are currently broken. Maybe a better approach would be to release that `??` along with whatever other syntactic sugar is needed in a 4.0.0 release after also announcing the webpack version compatibility change in the changelog.

**Comment by jeron-diovis** [comment]
@cherouvim With this configuration, `@react-leaflet/core 1.1.0` installs as dependency of `react-leaflet`, and explicit 1.0.2 is ignored. How did it work for you?

**Comment by cherouvim** [comment]
@jeron-diovis I'll redo this and confirm ASAP. I apologise in advance in case I got this totally wrong.

**Comment by cherouvim** [comment]
@jeron-diovis I used the exact version and I confirm that it works. Have a look at this (the 3rd block is the solution):
```
# Reproduce the problem with 3.2.0
cd /tmp
npx create-react-app error-3.2.0
cd error-3.2.0
npm install --save-exact leaflet@1.7.1
npm install --save-exact react-leaflet@3.2.0
printf "import React from 'react'; import ReactDOM from 'react-dom'; import { MapContainer } from 'react-leaflet'; const foo = <MapContainer />;" > src/index.js
npm start

# Reproduce the problem with 3.1.0
cd /tmp
npx create-react-app error-3.1.0
cd error-3.1.0
npm install --save-exact leaflet@1.7.1
npm install --save-exact react-leaflet@3.1.0
printf "import React from 'react'; import ReactDOM from 'react-dom'; import { MapContainer } from 'react-leaflet'; const foo = <MapContainer />;" > src/index.js
npm start

# Fix the problem with 3.1.0 + 1.0.2
cd /tmp
npx create-react-app fix-3.1.0-1.0.2
cd fix-3.1.0-1.0.2
npm install --save-exact leaflet@1.7.1
npm install --save-exact react-leaflet@3.1.0
npm install --save-exact @react-leaflet/core@1.0.2
printf "import React from 'react'; import ReactDOM from 'react-dom'; import { MapContainer } from 'react-leaflet'; const foo = <MapContainer />;" > src/index.js
npm start
```

**Comment by jeron-diovis** [comment]
@cherouvim I confirm your example works. 
But it appears, that somehow it works **only with npm**. My issue was that I used yarn.

With these deps:
```
"dependencies": {
    "@react-leaflet/core": "1.0.2",
    "react-leaflet": "3.1.0",
  },
```
I have following results:
```sh
> npm install
...

> ls node_modules/react-leaflet
LICENSE.md   README.md    cjs          esm          package.json types        umd

> grep 'react-leaflet/core' -O package-lock.json
        "@react-leaflet/core": "1.0.2",
    "node_modules/@react-leaflet/core": {
      "resolved": "https://registry.npmjs.org/@react-leaflet/core/-/core-1.0.2.tgz",
        "@react-leaflet/core": "^1.0.2"
    "@react-leaflet/core": {
      "resolved": "https://registry.npmjs.org/@react-leaflet/core/-/core-1.0.2.tgz",
        "@react-leaflet/core": "^1.0.2"

> rm -rf node_modules package-lock.json

> yarn
...

> ls node_modules/react-leaflet
LICENSE.md   README.md    cjs          esm          node_modules package.json types        umd

> grep 'react-leaflet/core' -O yarn.lock
"@react-leaflet/core@1.0.2":
  resolved "https://registry.yarnpkg.com/@react-leaflet/core/-/core-1.0.2.tgz#39c6a73f61c666d5dcf673741cea2672fa4bbae1"
"@react-leaflet/core@^1.0.2":
  resolved "https://registry.yarnpkg.com/@react-leaflet/core/-/core-1.1.0.tgz#389b2b373f1da4caeb3c4cf6f33d84561c58d504"
    "@react-leaflet/core" "^1.0.2"
```

As you can see, with yarn installation there are versions `1.0.2 -> 1.0.2` and `^1.0.2 -> 1.1.0` in lockfile.
Not sure is it just me, or smth is wrong with yarn.

**Comment by danmoka** [comment]
> @jeron-diovis I used the exact version and I confirm that it works. Have a look at this (the 3rd block is the solution):
> 
> ```
> # Reproduce the problem with 3.2.0
> cd /tmp
> npx create-react-app error-3.2.0
> cd error-3.2.0
> npm install --save-exact leaflet@1.7.1
> npm install --save-exact react-leaflet@3.2.0
> printf "import React from 'react'; import ReactDOM from 'react-dom'; import { MapContainer } from 'react-leaflet'; const foo = <MapContainer />;" > src/index.js
> npm start
> 
> # Reproduce the problem with 3.1.0
> cd /tmp
> npx create-react-app error-3.1.0
> cd error-3.1.0
> npm install --save-exact leaflet@1.7.1
> npm install --save-exact react-leaflet@3.1.0
> printf "import React from 'react'; import ReactDOM from 'react-dom'; import { MapContainer } from 'react-leaflet'; const foo = <MapContainer />;" > src/index.js
> npm start
> 
> # Fix the problem with 3.1.0 + 1.0.2
> cd /tmp
> npx create-react-app fix-3.1.0-1.0.2
> cd fix-3.1.0-1.0.2
> npm install --save-exact leaflet@1.7.1
> npm install --save-exact react-leaflet@3.1.0
> npm install --save-exact @react-leaflet/core@1.0.2
> printf "import React from 'react'; import ReactDOM from 'react-dom'; import { MapContainer } from 'react-leaflet'; const foo = <MapContainer />;" > src/index.js
> npm start
> ```

Worked for me. Thank you so match!

**Comment by gmarshall56** [comment]
I changed my package.json per @cherouvim  recommendation:
 "@react-leaflet/core": "1.0.2",
  "react-leaflet": "3.1.0",

I then did a npm install --force, because npm install without force throws errors.
Now, when I do a npm start I am getting this:

./node_modules/react-leaflet/esm/MapContainer.js
Module parse failed: Unexpected token (34:2)
You may need an appropriate loader to handle this file type.
|   style,
|   whenCreated,
|   ...options
| }) {
|   const mapRef = useRef(null);

This is not good at all.  This is a disaster.  If I have to roll back to version 2.7.0 of react leaflet I will have to redo a bunch of code that I had originally written to take advantage of MapContainer's whenCreated prop to set state when the map is rendered.  Now how do I do all of that using version 2.7.0, which does not have the MapContainer component defined in it?  This is going to set me and my team behind significantly in our development.  Can somebody put a fire under the a**es of the person / people who are responsible for this?  Maybe we should have used ArcGIS.

**Comment by slutske22** [comment]
> This is not an issue with React Leaflet but with your bundler or similar tool's support or configuration, please raise the issue in the relevant repository.

There are *alot* of duplicate issues going up in this repo surrounding this same issue.  I am also participating in the [create-react-app issue](https://github.com/facebook/create-react-app/issues/9468) surrounding this problem, which was just closed with the following [comment](https://github.com/facebook/create-react-app/issues/9468#issuecomment-853246141):

> This is an issue with third-party packages so there's not much we can do about it. Package authors should generally not be compiling for `esnext`. Consider opening an issue with those packages.

The tsconfig for react-leaflet uses `es2019`, which I guess still does not transpile `??` to more primitive syntax.  But I agree with the CRA comment.  Considering react-leaflet is the premier react wrapper for leaflet, and create-react-app is the premier tool for react applications, written by the same org that wrote react itself, I feel like react-leaflet should indeed comply with their compatibility requirements.  (Granted, I do not have this issue with a custom webpack/babel config and the latest version of react-leaflet, but I think CRA is a pretty good 'lowest-common-denominator' to shoot for in terms of compatibility of react component libraries).

@PaulLeCam how difficult would it really be to set `target` to `es2018`, or even something more primitive, like `es5`, rebuild, and republish under a minor version?  Putting the burden of transpilation on program authors for node modules is sort of bad practice.  I love react-leaflet, a lot, but I'm ready to throw my 🍅🍅🍅  as far as this issue is concerned.

**Comment by ATAKENNAME** [comment]
I got the same issues, and tried all the method mentioned in the facebook post, it didn't work. Any idea how to solve it?

**Comment by Frikster** [comment]
A PR is open to fix this issue [here](https://github.com/PaulLeCam/react-leaflet/pull/885).

It is taking a long time to merge so the PR author has provided a [temporary version of the package](https://github.com/PaulLeCam/react-leaflet/pull/885#issuecomment-854857931) you could install that should fix all issues.

I've also found downgrading react-leaflet to fix things:

```
"react-leaflet": ">=3.1.0 <3.2.0 || ^3.2.1",
"@react-leaflet/core": ">=1.0.0 <1.1.0 || ^1.1.1"
```

I'm using a pretty bare-bones create-react-app with react-leaflet. It makes more sense to me that downgrading this package leading to a fixed issue means there is a problem with the latest version of this package that needs to be addressed. react-leaflet should conform to and maintain compatibility with create-react-app, not the other way around.

**Comment by gmarshall56** [comment]
15 days ago I made my posting here along with my rant.  After placing that post I continued to trouble shoot this issue, chewing up much valuable development time.
After changing my package.json per @cherouvim recommendations, and starting with a fresh create-react-app, I discovered the version of react-scripts  ("^1.1.5") in my package.json was different than the version in the fresh create-react-app.  So, scrambling for a solution, I changed the version of react-scripts in my package.json to the same version that is in my fresh create-react-app ("4.0.3"), deleted the node_modules folder and the package-lock file and reinstalled with "npm install --force".  It then built successfully.
For me, this issue has given npm a big black eye, but perhaps I didn't know any better.  I was expecting npm to handle versioning issues the way that Spring Boot does.

**Comment by trevorr** [comment]
The best, long-term way to handle this for CRA users is to use `react-app-rewired` and `customize-cra` to transpile the latest version of react-leaflet to whatever version of JS you need: https://stackoverflow.com/a/67991412/123336

**Comment by teachermugabo** [comment]
> This is not an issue with React Leaflet but with your bundler or similar tool's support or configuration, please raise the issue in the relevant repository.

In closing this issue, it would be helpful to point folx to solutions. 

Customizing CRA (create-react-app) like so https://stackoverflow.com/a/67991412/558732 seems to be most promising but I still haven't gotten it to work yet.

**Comment by ucksylr** [comment]
> Removing node_modules/.cache worked for me. Thank to all!!!!

It works on me thank you

**Comment by alamothe** [comment]
It could be fixed with `patch-package`

**Comment by samirarezai** [comment]
`"react-scripts": "^5.0.1",`
I updated the react-scripts package using `yarn add react-scripts` then my problems disappeared.

**Comment by Etienne-M** [comment]
> This is not an issue with React Leaflet but with your bundler or similar tool's support or configuration, please raise the issue in the relevant repository.

That is 100% correct, but the fact remains that this isn't a niche bug. This library's sole purpose is to provide react bindings, and it will not bundle with the most common boilerplate for react. This means that first time users can't make this library work when following the installation steps, and when they go the list of issues, they can't find anything related to that...

It would be worth adding a note to the documentation. Something like: "This library is transpiled to es2019, which isn't supported by create-react-app. To circumvent the issue, try a library to amend the build config (react-app-rewired or craco), or eject and modify the config."

**Comment by kpennell** [comment]
Hey Folks - CRA user here. I followed the steps above and it seems? to work

Changing browser targets from

 "browserslist": {
   "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
},
to

"browserslist": [
   ">0.2%",
  "not dead",
  "not op_mini all"
],


then delete node_modules .cache

Re run `yarn start`

**Comment by weswithley** [comment]
This works for me with using Webpack only ( non-use CRA ) : 
- Remove the "node_modules" from "exclude" list in babel-loader. [ commnent 841883540 ]( https://github.com/PaulLeCam/react-leaflet/issues/877#issuecomment-841883540 )

![image](https://user-images.githubusercontent.com/4627590/176875675-3b8d712a-8d00-4e7c-8e82-4d741907053a.png)

- Reason :  [ comment 842993083 ]( https://github.com/PaulLeCam/react-leaflet/issues/877#issuecomment-842993083 )

Although I think including the whole node_modules folder into the loader for parsing purposes isn't the best idea, but currently works for me.
  
Btw, some comments say that need to use "@babel/plugin-proposal-nullish-coalescing-operator" plugin in babel-loader, but I didn't use this. [ comment 881117957 ]( https://github.com/PaulLeCam/react-leaflet/issues/881#issuecomment-881117957 )
