### ISSUE TITLE
Uncaught Error: Map container is already initialized with React v18 and Formik

### ISSUE THREAD

**Issue by IngusSkaistkalns** [PaulLeCam/react-leaflet#936]
## Bug report

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v17.0.0 minimum).
- [x] Using the supported version of Leaflet (v1.7.1 minimum) and its corresponding CSS file is loaded.
- [x] Using the [latest v3 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/start-introduction) and that you understand the [limitations](https://react-leaflet.js.org/docs/start-introduction#limitations).

**I understand that I have reported bug using React v18 RC version that has not been released yet, but I believe this will soon be raised anyway. If I have missed any posts regarding supporting React v18 - I apologise in advance**

* **React v18.0.0-rc.0-next-ceee524a8-20211217** ,
* **ReactDOM v8.0.0-rc.0-next-ceee524a8-20211217**, 
* **Formik  v2.2.9**;

 Using React v18 style `createRoot` + `render` API (https://github.com/reactwg/react-18/discussions/5) and with using library `Formik` (https://github.com/jaredpalmer/formik)  it is possible to catch moment when inside `useMapElement` hook `mapRef.current` is set,`map` is still null at the `if` statement, 

but when next instruction starts executing `const instance = new LeafletMap(mapRef.current, props);` map has been set, therefore this error happens:

```
Uncaught Error: Map container is already initialized.
```

This looks like an issue that could be related to Reacts v18 New root API: 
```
The new Root API is called with ReactDOM.createRoot. 
This creates a root running in React 18, which adds all of the improvements of React 18 and allows you to use concurrent features.
This will be the root API moving forward.
```

State variable `map` mutates within function execution.

Code where error happens inside react-leaflet:
https://github.com/PaulLeCam/react-leaflet/blob/master/packages/react-leaflet/src/MapContainer.tsx#L37:L38

This issue is not present if using old API  `ReactDOM.render`.

### Expected behavior

When navigating using `BrowserRouter` `NavLink` to component with map it is expected to render map without error.

### Actual behavior

When navigating using `BrowserRouter` `NavLink` to component with map - error happens.

![image](https://user-images.githubusercontent.com/219684/147094369-0441787e-02aa-4784-a0fd-e9bc5589151f.png)

But if you navigate to specific page url directly with refresh - then it always work.
Go away from page with map and come back - error happens.

### Steps to reproduce

I did not manage to setup example in code pen (I apologise again), 
this is the shortest reproducible example I come up with:

```tsx
import React, { useEffect } from 'react'
import ReactDOM from 'react-dom'
import { NavLink, Route, Routes, BrowserRouter } from 'react-router-dom'
import { Form, FormikProvider, useFormik, useFormikContext } from 'formik'
import { MapContainer } from 'react-leaflet'

const rootElement = document.getElementById('root')
const root = ReactDOM.createRoot(rootElement)

const App = () => {
  return (
    <Routes>
      <Route path='/' element={<IndexApp />} />
      <Route path='/form' element={<FormApp />} />
    </Routes>
  )
}

const IndexApp = () => {
  return <h1>Index</h1>
}

const FormApp = () => {
  const formikProps = useFormik({
    enableReinitialize: false,
    initialValues: { time: 0 },
    onSubmit: () => {},
  })

  return (
    <FormikProvider value={formikProps}>
      <FormWithEffectAndContainer />
    </FormikProvider>
  )
}

const FormWithEffectAndContainer = () => {
  const { setFieldValue } = useFormikContext()

  useEffect(() => {
    // With this formik method call it is possible to reproduce error always!
    setFieldValue('time', 1)
  }, [])

  return (
    <Form>
      <MapContainer center={[56.95, 24.1]} zoom={12} />
    </Form>
  )
}

root.render(
  <BrowserRouter>
    <NavLink to={'/'}>Index</NavLink>
    <NavLink to={'/form'}>Form</NavLink>
    <App />
  </BrowserRouter>
)

```

1) Click on `Index` link,
2) click on `Form` link - error happens.

*NOTE:* I was not able to reproduce error without using `formik` library! I assume it is possible, but there just have to be something "special", that we have not yet discovered, since this looks like React related thing.

### Possible hacks to get around at the moment

Set explicit `key={new Date().getTime()}` for MapContainer and error does not happen.

**Comment by PaulLeCam** [comment]
v3 won't work with React v18, at least when using concurrent mode.
Please try out the [v4 alpha](https://github.com/PaulLeCam/react-leaflet/releases/tag/v4.0.0-alpha.1) that targets React v18!

**Comment by WarrenWilkinson** [comment]
Thank you so much for that workaround, I've been wrestling with this issue on react-leaflet/core 2.0.0,  leaflet 1.8.0, react-leaflet: 4.0.0, react 18.1.0 and react-dom 18.1.0.    Adding `key={new Date().getTime()} `, like you suggested as a work around has fixed this for me.  Without it I get the same error you mentioned.

**Comment by tbowmo** [comment]
I'm still getting this error. I have several sub pages, each with a map container defined. The first page loads ok, but if I then go to the next sub page, I get the error.. The trick with adding `key={new Date().getTime()}` does fix the issue for the moment, but it also creates a memory leak, as the domNode increases in size for each new page render.

I tried to add a React.useEffect() to call leafletMap.remove() when my component unmounts. But that crashes the site, whenever it tries to show a map.

**Comment by Hassaangithub** [comment]
i am using 
    "@react-leaflet/core": "^2.0.0",
    "leaflet": "^1.8.0",
    "react-leaflet": "^4.0.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    
    still getting MapContainer is already initialized, when map component rerender. try all available issues but nothing fix it.
    **if i use map.remove() in mounting or unmounting,**
    it throw error: "map container is being used by other instances".
    
    @PaulLeCam

**Comment by denis-heise** [comment]
I am using:
"@react-leaflet/core": "2.1.0",
"leaflet": "^1.9.0",
"react-leaflet": "^4.2.0",
"react": "^18.0.0",
"react-dom": "^18.0.0",

And i still get the error "Uncaught Error: Map container is already initialized"

**Comment by steps371** [comment]
Same here, still getting this issue.

Ideally, I wouldn't want to force remount by specifying a unique key, as it caused 'jankiness' in the UI

**Comment by MuhammadArsalanAhmed** [comment]
I'd been stuck in this problem, then I thought about this solution. It works for me.




const [unmountMap, setunmountMap] = useState(false);
//to prevent map re-initialization
  useLayoutEffect(() => {
    setunmountMap(false);
    return () => {
      // console.log("unmounting!", mapRef);
      setunmountMap(true);
    };
  }, []);
  
  
   if (!unmountMap)
    return (
      <MapContainer  ></MapContainer>
    );
  else return "loading map...";

**Comment by leandronn** [comment]
> I'd been stuck in this problem, then I thought about this solution. It works for me.
> 
> const [unmountMap, setunmountMap] = useState(false); //to prevent map re-initialization useLayoutEffect(() => { setunmountMap(false); return () => { setunmountMap(true); }; }, []);
> 
> if (!unmountMap) return ( ); else return "loading map...";

This solution works for me

"react": "18.2.0",
"react-leaflet": "^4.2.0",
"leaflet": "^1.9.3",
"@react-leaflet/core": "^2.1.0",
"next": "13.1.1",

**Comment by denis-heise** [comment]
Hello.
I did not immediately understand what you mean (I wrote about it for a long
time).
Thank you for taking the time and giving me an answer.

ср, 2 авг. 2023 г. в 19:14, leandronn ***@***.***>:

**Comment by ekimcem** [comment]
Still have the same problem with current stack;

    
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "next": "^13.5.0",
    "leaflet": "1.9.2",
    "react-leaflet": "^4.2.1",

**Comment by quiloos39** [comment]
I have no idea if this is a good approach but following fixed for me

```typescript
const StoreMap = useMemo(() => dynamic(() => import('./StoreMap').then((mod) => mod.StoreMap), { ssr: false }), []);
```

**Comment by lajtmaN** [comment]
I fixed this issue by wrapping the `children` of the `MapContainer` in a `Suspense`:
```jsx
<MapContainer {...options}>
  <Suspense>
    {children}
  </Suspense>
</MapContainer>
```

That is the only change I have made - I'm not using dynamic imports, a `key` with current time, layout effect to check when unmounted etc. Just wrapping children in Suspense was enough for me. 

I'm using these versions:
```
"leaflet": "1.9.4",
"react-leaflet": "4.2.1",
"react": "18.3.1",
```

**Comment by chrissakiki** [comment]
Wrap your Leaflet component with React.memo
this will do the job.

**Comment by maxbodin** [comment]
Same here, still getting "Error: Map container is already initialized." with :
    "leaflet": "^1.9.4",
    "leaflet-defaulticon-compatibility": "^0.1.2",
    "next": "^15.0.2",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "react-leaflet": "^4.2.1"
    
Tried each solution but none worked.

**Comment by luthfikhan** [comment]
Works for me

```JavaScript
useEffect(() => {
  return () => {
    const m = L.DomUtil.get("map") as (HTMLElement & { _leaflet_id: number | null }) | null;
    if (m) {
      m._leaflet_id = null;
    }
  };
}, []);
```

Versions
```
"leaflet": "^1.9.4",
"next": "^15.0.3",
"react": "^18.3.1",
"react-leaflet": "^4.2.1"
```

**Comment by maxbodin** [comment]
@luthfikhan Thanks for the suggestion! Our team has actually decided to switch over to React with Vite instead of using Next.js. But thanks for your help anyway; we appreciate it!

**Comment by IvanRiveraN** [comment]
> I fixed this issue by wrapping the `children` of the `MapContainer` in a `Suspense`:
> 
> <MapContainer {...options}>
>   <Suspense>
>     {children}
>   </Suspense>
> </MapContainer>
> 
> That is the only change I have made - I'm not using dynamic imports, a `key` with current time, layout effect to check when unmounted etc. Just wrapping children in Suspense was enough for me.
> 
> I'm using these versions:
> 
> ```
> "leaflet": "1.9.4",
> "react-leaflet": "4.2.1",
> "react": "18.3.1",
> ```

i am using this same deps, tried wrapping the children as you suggest (removed the dynamic import) but i still get the error
